DNNCommunity/DNN.Events

- Controls/DotNetNuke.Events.ScheduleControl/My Project/AssemblyInfo.vb
- Events.ascx.vb
- SubControls/App_LocalResources/EventIcons.ascx.resx
- SubControls/EventIcons.ascx
- SubControls/EventIcons.ascx.designer.vb
- SubControls/EventIcons.ascx.vb
Goes together with branch "Issue_25959".
> Editing locations and categories from menu bar.

- Components/EventController.vb
Hi,
I believe I've found and solved the cause of some issues. On the City of Prince Albert website we are using this event module, and it stopped displaying events on a month. There didn't seem to be any rhyme or reason to which months did or did not work.
I came across #48 when looking for solutions, and decided to dig into the code myself. The only way I was able to reproduce the issue was by copying my production event data into my development environment and patch up the module/user id's.
Line 350 in EventController.vb was throwing an exception: Unable to sort because the IComparer.Compare() method returns inconsistent results. Either a value does not compare equal to itself, or one value repeatedly compared to another value yields different results
The cast from a boolean to a …
> Fix broken EventDateSort causing blank or missing events on calendar

- Components/EventController.cs
- EditEvents.ascx.cs
- EventDay.ascx.cs
- EventDetails.ascx.cs
- EventEditCategories.ascx.cs
- EventEditLocations.ascx.cs
- EventModerate.ascx.cs
- EventPPEnroll.ascx.cs
- EventSettings.ascx.cs
- EventTemplateHelp.ascx.cs
- Events.ascx.cs
- Settings.ascx.cs
<a href='https://www.codereviewhub.com/DNNCommunity/DNN.Events/pull/78?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/DNNCommunity/DNN.Events/pull/78'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Small fix for build problems due to clean up

- Controls/DotNetNuke.Events.ScheduleControl/Properties/AssemblyInfo.cs
- DotNetNuke.Events.csproj
- Installation/DNN_Events.dnn
- Installation/ReleaseNotes/Release.07.00.01.txt
- Properties/AssemblyInfo.cs
<a href='https://www.codereviewhub.com/DNNCommunity/DNN.Events/pull/86?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/DNNCommunity/DNN.Events/pull/86'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Updated the version # to 7.0.1 and created release notes

- Installation/CleanUp/Cleanup.07.00.02.txt
* **Please check if the PR fulfills these requirements**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Cleanup
* **What is the current behavior?** (You can also link to an open issue here)
No cleanup
* **What is the new behavior (if this is a feature change)?**
Cleanup of .pdb
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No
* **Other information**:
-
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/DNNCommunity/DNN.Events/pull/89%23issuecomment-399754913%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/DNNCommunity/DNN.Events/pull/89%23issuecomment-399754913%22%2C%2 …
> #Close 88 pdb cleanup for the next release

- EventList.ascx.cs
- Installation/ReleaseNotes/Release.07.00.02.txt
Fixed an issue where it was impossible to exit list view mode
- Fixed a dataitem null reference that was probably caused by the vb to c# conversion
Close #80 
Close #97
<a href='https://www.codereviewhub.com/DNNCommunity/DNN.Events/pull/104?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/DNNCommunity/DNN.Events/pull/104'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Fixed an issue where it was impossible to exit list view mode

- SubControls/SelectCategory.ascx.cs
fixes invalid cast when filtering by Category is used in module settings (not the dropdown in module heading)
changed "foreach … int" to "foreach … var"
- [ X ] Fixes Bug
rather than raise a new issue, I thought I would try to fix it
Close #
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/DNNCommunity/DNN.Events/pull/112%23issuecomment-406798336%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/DNNCommunity/DNN.Events/pull/112%23issuecomment-406798336%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Looks%20fine%20to%20me.%20%22%2C%20%22created_at%22%3A%20%222018-07-21T13%3A55%3A38Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars1.githubusercontent.com/u/5859 …
> fix for invalid cast when filtering by category

- Components/EventController.cs
- Item 1
- Item 2
Close #
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/DNNCommunity/DNN.Events/pull/113%23issuecomment-406718476%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/DNNCommunity/DNN.Events/pull/113%23issuecomment-406718476%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Looks%20good%20to%20me%22%2C%20%22created_at%22%3A%20%222018-07-20T20%3A30%3A11Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/6371568%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/valadas%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'><img …
> Finished bug #94

- EventModerate.ascx.cs
- EventRpt.ascx.cs
Fixes issue #120
<a href='https://www.codereviewhub.com/DNNCommunity/DNN.Events/pull/121?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/DNNCommunity/DNN.Events/pull/121'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Fixes issue #120 & #110

- EventModerate.ascx.cs
- EventRpt.ascx.cs
Fix for #109
<a href='https://www.codereviewhub.com/DNNCommunity/DNN.Events/pull/122?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/DNNCommunity/DNN.Events/pull/122'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Fix for #109

- Components/EventModuleSettings.cs
- EditEvents.ascx
- EditEvents.ascx.cs
- EventModerate.ascx.cs
- EventRpt.ascx.cs
A number of methods have become broken after the vb conversion process. These have been identified and are working again.
<a href='https://www.codereviewhub.com/DNNCommunity/DNN.Events/pull/124?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/DNNCommunity/DNN.Events/pull/124'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Finished the PBI #116

- Controls/DotNetNuke.Events.ScheduleControl/DotNetNuke.Events.ScheduleControl.csproj
- Controls/DotNetNuke.Events.ScheduleControl/Properties/AssemblyInfo.cs
- DotNetNuke.Events.csproj
- Properties/AssemblyInfo.cs
Update version # 
<a href='https://www.codereviewhub.com/DNNCommunity/DNN.Events/pull/125?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/DNNCommunity/DNN.Events/pull/125'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Update version # for the next release

- Installation/CleanUp/Cleanup.07.00.03.txt
- Installation/DNN_Events.dnn
- Installation/Project.targets
- Installation/ReleaseNotes/Release.07.00.03.txt
<a href='https://www.codereviewhub.com/DNNCommunity/DNN.Events/pull/131?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/DNNCommunity/DNN.Events/pull/131'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Update version info

- Components/iCalProvider.cs
<a href='https://www.codereviewhub.com/DNNCommunity/DNN.Events/pull/132?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/DNNCommunity/DNN.Events/pull/132'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Close #130: substr out of range

- EventSettings.ascx
- EventSettings.ascx.cs
Close #128
Added additional click event link in code behind
Close #128 
Close #
<a href='https://www.codereviewhub.com/DNNCommunity/DNN.Events/pull/135?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/DNNCommunity/DNN.Events/pull/135'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Template save & rest fixed.

- Components/EventBase.cs
- Components/EventController.cs
- Components/EventInfo.cs
- Components/EventModuleSettings.cs
- Components/EventModuleTemplates.cs
- Components/EventNotification.cs
- Components/EventTokenReplace.cs
- Components/Integration/Content.cs
- Components/SiteMapProvider.cs
- Components/SqlDataProvider.cs
Cleanup converte code
this. removed
Close #133
<a href='https://www.codereviewhub.com/DNNCommunity/DNN.Events/pull/136?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/DNNCommunity/DNN.Events/pull/136'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Code cleanup. Close #133

- Components/EventModuleSettings.cs
- Installation/DNN_Events.dnn
Mapping of settings names vs table values
- Item 1
- Item 2
Close #146
<a href='https://www.codereviewhub.com/DNNCommunity/DNN.Events/pull/147?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/DNNCommunity/DNN.Events/pull/147'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Close #146, casing of the names of the settings in code vs database

- Installation/ReleaseNotes/Release.07.00.03.txt
See title
<a href='https://www.codereviewhub.com/DNNCommunity/DNN.Events/pull/148?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/DNNCommunity/DNN.Events/pull/148'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Update release notes

- EditEvents.ascx.cs
- EventDetails.ascx.cs
- EventEditCategories.ascx.cs
- EventEditLocations.ascx.cs
- EventModerate.ascx.cs
- EventSettings.ascx.cs
- Installation/DNN_Events.dnn
> Correct dnn manifest generation

- EditEvents.ascx.cs
- EventDay.ascx.cs
- EventDetails.ascx.cs
- EventEditCategories.ascx.cs
- EventEditLocations.ascx.cs
- EventModerate.ascx.cs
- EventSettings.ascx.cs
- EventTemplateHelp.ascx.cs
- Installation/DNN_Events.dnn
> Issue 156b

- Components/EventTokenReplace.cs
Issue #168
List View Event Title Category Font Color not Respected 
Add style color to <a href event title
- [x ] Fixes Bug
Close #168
> Fixes issue List View Event Title Category Font Color not Respected.

- EditEvents.ascx.cs
Fixes issue Priority on Edit Series Reverts to Normal. Issue #151
Change comparing dropdown selected from value to text 
- [x ] Fixes Bug
Close #151
> Fixes issue Priority on Edit Series Reverts to Normal. Issue #151

- Installation/CleanUp/Cleanup.07.00.03.txt
Improved cleanup file to remove a wrong folder with subfolders in the Events Desktopmodules folder
Close #155
> Close #155: improved cleanup file for 07.00.03

- Themes/Default/Default.css
- Themes/Events-Green/Events-Green.css
- Themes/Events-Grey/Events-Grey.css
- Themes/Events-Orange/Events-Orange.css
- Themes/Events/Events.css
- Themes/FixedBlue/FixedBlue.css
- Themes/Gray/Gray.css
- Themes/MinimalExtropy/MinimalExtropy.css
- Themes/Small/Small.css
Uncompressed CSS in source
- All theme css files
Close #177
> Close #177

- Components/EventModuleSettings.cs
- Installation/07.00.04.SqlDataProvider
- Installation/DNN_Events.dnn
All settings names straightened for UPPER and lower case as attribute name and data in the settings table
- Straightened settings attribute name
- Update all settings records to match the case of setting the attribute name
Close #161
> Close #161.

- Settings.ascx.cs
- SubControls/EventUserGrid.ascx
- SubControls/EventUserGrid.ascx.cs
Closes #184
- Correct wrong code language file
- SOme code improvements
Close #184
> Update text and code optimizations.

- Components/EventModuleSettings.cs
- Controls/DotNetNuke.Events.ScheduleControl/DNNCalendar.cs
- Controls/DotNetNuke.Events.ScheduleControl/baseschedule.cs
- Controls/DotNetNuke.Events.ScheduleControl/calendarpropertybuilder.cs
- Controls/DotNetNuke.Events.ScheduleControl/clickabletablecell.cs
- Controls/DotNetNuke.Events.ScheduleControl/clickabletablecelleventargs.cs
- Controls/DotNetNuke.Events.ScheduleControl/schedulecalendar.cs
- Controls/DotNetNuke.Events.ScheduleControl/schedulecommandeventargs.cs
- Controls/DotNetNuke.Events.ScheduleControl/schedulegeneral.cs
- Controls/DotNetNuke.Events.ScheduleControl/scheduleitem.cs
- Controls/DotNetNuke.Events.ScheduleControl/scheduleitemcollection.cs
- Controls/DotNetNuke.Events.ScheduleControl/scheduleitemeventargs.cs
- EventPPEnroll.ascx.cs
- SubControls/SelectCategory.ascx.cs
- SubControls/SelectLocation.ascx.cs
> Removed rendundant qualifiers due to C# conversion

- Installation/ReleaseNotes/Release.07.00.04.txt
> Release notes 07.00.04

- SubControls/App_LocalResources/EventIcons.ascx.resx
- SubControls/EventIcons.ascx
Close #181
Added alt text to buttons in iconbar
> Added text descriptions to buttons

- App_LocalResources/EditEvents.ascx.resx
- EditEvents.ascx
Close #93
Updates descriptions of text boxes
Improves lay-out of edit Rich Textbox
> Updates labels to make it more readable, update margin of text boxes

- Installation/ReleaseNotes/Release.07.00.04.txt
> Update release notes typo

- README.md
> Closes #196, update readme

- README.md
Spacing in file names in URL of picture
> Updates issue #196

- Components/EventBase.cs
- Components/EventModuleSettings.cs
- EditEvents.ascx
- EditEvents.ascx.cs
- EventDetails.ascx.cs
- EventMonth.ascx
- EventRSS.aspx.cs
- EventWeek.ascx
Month and Week views date picker fix
- selecting a date on the month view did not work
- selecting a date on the week view did not work
- [x ] Fixes Bug
Close #
> Month and Week views date picker fix

- Controls/DotNetNuke.Events.ScheduleControl/Properties/AssemblyInfo.cs
- Installation/CleanUp/Cleanup.07.00.05.txt
- Installation/DNN_Events.dnn
- Installation/ReleaseNotes/Release.07.00.05.txt
- Properties/AssemblyInfo.cs
- SubControls/SelectLocation.ascx.cs
> Release items

- .github/stale.yml
> Update stale message text

- .github/stale.yml
> Update text of message

- Controls/DotNetNuke.Events.ScheduleControl/Properties/AssemblyInfo.cs
- EventDetails.ascx
- Installation/CleanUp/Cleanup.07.00.06.txt
- Installation/DNN_Events.dnn
- Installation/ReleaseNotes/Release.07.00.06.txt
- Properties/AssemblyInfo.cs
> Release things

- Installation/07.00.07.SqlDataProvider
> Correct OQ en DBO in the script

- EventMonth.ascx
- EventWeek.ascx
- SubControls/SelectCategory.ascx
- SubControls/SelectLocation.ascx
Confirm to WAVE specifications
> Link labels to controls
